"use client"
import { DataTable } from "@/components/data-table";
import data from "./reports.json"


export default function Page() {

   

 const reportsColumns  = [
  { accessorKey: "id", header: "id" },
  { accessorKey: "title", header: "title" },
  { accessorKey: "type", header: "type" },
  { accessorKey: "generatedBy", header: "generated by" },
  { accessorKey: "generatedAt", header: "generated at" },
  { accessorKey: "status", header: "status" },
]
    return (
        <div className=" m-6">

                
            <DataTable data={data}
             columns={reportsColumns}/>
        </div>
    )
}